services:
  node-red:
    image: nodered/node-red:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - '1880:1880'
    # volumes:
    #   - ./node_red_data:/data
    # environment:
    #   - DISABLE_ADDITIONAL_FEATURES=false
    #   - LANGS=en_GB
